<?php

$crl[0]='48';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=windows-1250">';
$crl[2]='Chat plechotice.sk';
$crl[3]='Sound: On/Off';
$crl[4]='Poslať';
$crl[5]='Zrušiť';
$crl[6]='Heslo';
$crl[7]='Zmeniť farby...';
$crl[8]='NAHNEVANÝ';
$crl[9]='V POHODE';
$crl[10]='SMUTNÝ';
$crl[11]='NADŠENÝ';
$crl[12]='USMIEVAVÝ';
$crl[13]='ZACHMÚRENÝ';
$crl[14]='TEXT TUČNE';
$crl[15]='TEXT KURZÍVOU';
$crl[16]='TEXT FAREBNE';
$crl[17]='Dátum / Čas';
$crl[18]='Prezývka';
$crl[19]='Správa';
$crl[20]='HISTÓRIA ( 150 riadkov )';
$crl[21]='Táto stránka potrebuje prehliadač s podporou rámcov.';
$crl[22]='Online užívatelia';
$crl[23]='Nikto nie je prihlásený';
$crl[24]='Prihlásiť sa ako';
$crl[25]='Chat';
$crl[26]='Vstúpiť do chatu [ aktualizovať ]';
$crl[27]='História';
$crl[28]='Prezrieť si históriu [ aktualizovať ]';
$crl[29]='Odhlásiť';
$crl[30]='Odhlásiť [ zmeniť prezývku ]';
$crl[31]='Vymazať';
$crl[32]='Vymazať chat a históriu [ chránené heslom ]';
$crl[33]='O chatu';
$crl[34]='Aktualizovať: ';
?>