<?php 
/* Italiano*/

$crl[0]='4';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">';
$crl[2]='Sopravvoliamo Online! - Chat';
$crl[3]='Suono: On/Off';
$crl[4]='Invia';
$crl[5]='Cancella';
$crl[6]='Password';
$crl[7]='Cambia i colori...';
$crl[8]='ARRABBIATO';
$crl[9]='FIGO';
$crl[10]='TRISTE';
$crl[11]='SORPRESO';
$crl[12]='SORRISO';
$crl[13]='OCCHIOLINO';
$crl[14]='GRASSETTO';
$crl[15]='ITALIC';
$crl[16]='COLORE';
$crl[17]='Data / Ora';
$crl[18]='Nickname';
$crl[19]='Messaggio';
$crl[20]='Aggiorna!';
$crl[21]='Questa pagina necessita di un browser che supporti i frame';
$crl[22]='Utenti Online!';
$crl[23]='Utenti non Online!';
$crl[24]='Nick';
$crl[25]='Aggiorna';
$crl[26]='Ricarica la pagina!';
$crl[27]='Messaggi passati';
$crl[28]='Leggi i vecchi messaggi';
$crl[29]='Esci';
$crl[30]='Esci dalla Chat';
$crl[31]='Amministratore';
$crl[32]='Area Protetta';
$crl[33]='Informazioni';
$crl[34]='Ordine Cronologico dei Messaggi';
?>
