<?php 
/* Norwegian */

$crl[0]='4';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Lyd: På/Av';
$crl[4]='Send';
$crl[5]='Avbryt';
$crl[6]='Passord';
$crl[7]='Endre farger...';
$crl[8]='ARG';
$crl[9]='COOL';
$crl[10]='TRIST';
$crl[11]='OVERRASKET';
$crl[12]='LER';
$crl[13]='BLUNKER';
$crl[14]='FET';
$crl[15]='KURSIV';
$crl[16]='FARGE';
$crl[17]='Dato / Tid';
$crl[18]='Navn';
$crl[19]='Melding';
$crl[20]='HISTORIE (150 linjer)';
$crl[21]='Denne siden krever en browser som støtter frames.';
$crl[22]='Brukere Online';
$crl[23]='Ingen brukere Online...';
$crl[24]='Navn';
$crl[25]='Chat';
$crl[26]='Gå til chat [Oppdater]';
$crl[27]='Historie';
$crl[28]='Gå til historie [Oppdater]';
$crl[29]='Logg Ut';
$crl[30]='Logg ut [Endre navn]';
$crl[31]='Slett';
$crl[32]='Slett chat og historie [Passordbeskyttet]';
$crl[33]='Om';
$crl[34]='Oppdater: ';
?>